development:
  public_host_username: fb
  public_host: fbdev2.railorz.com
  public_port: 3302
  local_port: 3302
  server_alive_interval: 0

test:
  public_host_username: 
  public_host: 
  public_port: 4007
  local_port: 3000
  server_alive_interval: 0

production:
  public_host_username: 
  public_host: 
  public_port: 4007
  local_port: 3000
  server_alive_interval: 0
