#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'

Delayed::Worker.sleep_delay = 1
Delayed::Command.new(ARGV).daemonize